### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Documents\\TMInterface\\Plugins\\Python_Link.as'

### ISSUE THREAD

**Issue by Cedri4** [Linesight-RL/linesight#87]
(linesight) C:\Users\Desktop\linesight>python scripts/train.py
SUCCESS: The process "TmForever.exe" with PID 29356 has been terminated.
Traceback (most recent call last):
  File "C:\Users\Desktop\linesight\scripts\train.py", line 97, in <module>
    shutil.copyfile(
  File "C:\Users\miniconda3\envs\linesight\Lib\shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\User\\Documents\\TMInterface\\Plugins\\Python_Link.as'

I tried downloading modloader but no success also in TM Modloader I have TMInterface selected.

**Comment by Cedri4** [comment]
Same problem as #31 but he didn't said how to fix it.

**Comment by heyitshestia** [comment]
Same issue here too. IDK how someone can just say "figured it out" and close the thread...

**Comment by sudafps** [comment]
go to Documents\TMInterface\Plugins and take the Python_Link.as file from linesight-3.0.0\linesight-3.0.0\trackmania_rl\tmi_interaction and copy and paste it to the Documents\TMInterface\Plugins folder

**Comment by LWY2012-code** [comment]
change target_python_link_path in user_config.py to a specific route
